export const users=[
  { 
    id:1,
    email:"user1@gmail.com",
    password:"abcxyz"
  },
  { 
    id:2,
    email:"user2@gmail.com",
    password:"abcxyz"
  },
  { 
    id:3,
    email:"user3@gmail.com",
    password:"abcxyz"
  },
  { 
    id:4,
    email:"user4@gmail.com",
    password:"abcxyz"
  },
  { 
    id:5,
    email:"user5@gmail.com",
    password:"abcxyz"
  },
  { 
    id:6,
    email:"user6@gmail.com",
    password:"abcxyz"
  },
  { 
    id:7,
    email:"user7@gmail.com",
    password:"abcxyz"
  },
  { 
    id:8,
    email:"user8@gmail.com",
    password:"abcxyz"
  },
  { 
    id:9,
    email:"user9@gmail.com",
    password:"abcxyz"
  },
  { 
    id:10,
    email:"user10@gmail.com",
    password:"abcxyz"
  }
] 